Support multi runners for services
mesg-foundation/js-sdk pull request #235
Opened 2020-04-14 04:57 UTC by antho1404

fix #232

We can now run multiple instances of the same service without having any conflicts in the container created

2020-04-14 04:57 UTC, antho1404 commented on packages/runner/CHANGELOG.md
> +- [#](https://github.com/mesg-foundation/js-sdk/pull/) Fix docker container names to support multi instances fix #232
```suggestion
- [#235](https://github.com/mesg-foundation/js-sdk/pull/235) Fix docker container names to support multi instances fix #232
```

2020-04-14 10:49 UTC, NicolasMahe requested changes
You need it change the network also:
https://github.com/mesg-foundation/js-sdk/blob/bcd6a6cede969a471fc105a02a29d9baa827b263/packages/runner/src/providers/container/index.ts#L48-L51
and in volume name:
https://github.com/mesg-foundation/js-sdk/blob/bcd6a6cede969a471fc105a02a29d9baa827b263/packages/runner/src/providers/container/index.ts#L186-L195

2020-04-14 10:52 UTC, NicolasMahe commented
Not related to this PR but can be fixed here:
The alias of the service on the engine's network seems wrong:
https://github.com/mesg-foundation/js-sdk/blob/bcd6a6cede969a471fc105a02a29d9baa827b263/packages/runner/src/providers/container/index.ts#L102
it should simply not be set.

2020-04-14 17:00 UTC, antho1404 commented
good catch, fixed

2020-04-15 05:55 UTC, NicolasMahe approved these changes

2020-04-15 07:07 UTC, merged